# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18]
        os: [ubuntu-latest]

    steps:
    - name: deploy
      uses: appleboy/ssh-action@main
      with:
        host:${{secrets.HOST}}
        username:${{secrets.USERNAME}}
        # key :${{secrets.KEY}}
        password:${{secrets.PASSWORD}}
        port:${{secrets.PORT}}
        scripts:
         export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd /root/demo-backend
          git pull origin main
          npm install --production
          npm run stop
          npm run start